/*
 * Copyright (C) 2023 Prof. Dr. David Buzatto
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package br.com.davidbuzatto.yaas.gui;

import br.com.davidbuzatto.yaas.gui.model.State;
import br.com.davidbuzatto.yaas.gui.model.Transition;

/**
 *
 * @author Prof. Dr. David Buzatto
 */
public class DFAInternalFrame extends javax.swing.JInternalFrame {

    private int xPressed;
    private int yPressed;
    
    private int xOffset;
    private int yOffset;
    
    private int currentState;
    
    private State selectedState;
    private Transition selectedTransition;
    
    /**
     * Creates new form DFAInternalFrame
     */
    public DFAInternalFrame() {
        initComponents();
        customInit();
    }

    private void customInit() {
        
        State s1 = new State();
        s1.setX1( 100 );
        s1.setY1( 200 );
        s1.setLabel( "q" + currentState++ );
        
        State s2 = new State();
        s2.setX1( 300 );
        s2.setY1( 100 );
        s2.setLabel( "q" + currentState++ );
        
        State s3 = new State();
        s3.setX1( 500 );
        s3.setY1( 100 );
        s3.setLabel( "q" + currentState++ );
        
        State s4 = new State();
        s4.setX1( 300 );
        s4.setY1( 300 );
        s4.setLabel( "q" + currentState++ );
        
        Transition t1 = new Transition( s1, s2, 'a' );
        Transition t2 = new Transition( s1, s4, 'a' );
        Transition t3 = new Transition( s2, s3, 'a' );
        Transition t4 = new Transition( s3, s4, 'a' );
        
        drawPanel.addState( s1 );
        drawPanel.addState( s2 );
        drawPanel.addState( s3 );
        drawPanel.addState( s4 );
        drawPanel.addTransition( t1 );
        drawPanel.addTransition( t2 );
        drawPanel.addTransition( t3 );
        drawPanel.addTransition( t4 );
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        toolBar = new javax.swing.JToolBar();
        btnMove = new javax.swing.JToggleButton();
        btnAddState = new javax.swing.JToggleButton();
        btnAddTransition = new javax.swing.JToggleButton();
        sep01 = new javax.swing.JToolBar.Separator();
        btnReset = new javax.swing.JButton();
        chkShowTCP = new javax.swing.JCheckBox();
        drawPanel = new br.com.davidbuzatto.yaas.gui.DrawPanel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("DFA");

        toolBar.setRollover(true);

        btnGroup.add(btnMove);
        btnMove.setSelected(true);
        btnMove.setText("move");
        btnMove.setFocusable(false);
        btnMove.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMove.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(btnMove);

        btnGroup.add(btnAddState);
        btnAddState.setText("add state");
        btnAddState.setFocusable(false);
        btnAddState.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddState.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(btnAddState);

        btnGroup.add(btnAddTransition);
        btnAddTransition.setText("add transition");
        btnAddTransition.setFocusable(false);
        btnAddTransition.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddTransition.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(btnAddTransition);
        toolBar.add(sep01);

        btnReset.setText("reset");
        btnReset.setFocusable(false);
        btnReset.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReset.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(btnReset);

        chkShowTCP.setText("show transition control points");
        chkShowTCP.setFocusable(false);
        chkShowTCP.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        chkShowTCP.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        chkShowTCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkShowTCPActionPerformed(evt);
            }
        });
        toolBar.add(chkShowTCP);

        drawPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                drawPanelMouseDragged(evt);
            }
        });
        drawPanel.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                drawPanelMouseWheelMoved(evt);
            }
        });
        drawPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                drawPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                drawPanelMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout drawPanelLayout = new javax.swing.GroupLayout(drawPanel);
        drawPanel.setLayout(drawPanelLayout);
        drawPanelLayout.setHorizontalGroup(
            drawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        drawPanelLayout.setVerticalGroup(
            drawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 533, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolBar, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
            .addComponent(drawPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(toolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(drawPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void drawPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drawPanelMousePressed
        
        xPressed = evt.getX();
        yPressed = evt.getY();
        
        if ( btnMove.isSelected() ) {
            
            selectedState = drawPanel.getStateAt( xPressed, yPressed );
            
            if ( selectedState != null ) {
                xOffset = xPressed - selectedState.getX1();
                yOffset = yPressed - selectedState.getY1();
                drawPanel.updateTransitions();
            } else {
                selectedTransition = drawPanel.getTransitionAt( xPressed, yPressed );
            }
            
        } else if ( btnAddState.isSelected() ) {
            
            State newState = new State();
            newState.setX1( xPressed );
            newState.setY1( yPressed );
            newState.setLabel( "q" + currentState++ );
            
            drawPanel.addState( newState );
            
        } else if ( btnAddTransition.isSelected() ) {
            
        }
        
        drawPanel.repaint();
        
    }//GEN-LAST:event_drawPanelMousePressed

    private void drawPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drawPanelMouseReleased
        
        selectedState = null;
        
        if ( selectedTransition != null ) {
            selectedTransition.mouseReleased( evt );
            selectedTransition = null;
        }
        
    }//GEN-LAST:event_drawPanelMouseReleased

    private void drawPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drawPanelMouseDragged
        
        if ( selectedState != null ) {
            selectedState.setX1( evt.getX() - xOffset );
            selectedState.setY1( evt.getY() - yOffset );
            drawPanel.updateTransitions();
            drawPanel.draggTransitions( evt );
        } else if ( selectedTransition != null ) {
            selectedTransition.mouseDragged( evt );
        }
        
        drawPanel.repaint();
        
    }//GEN-LAST:event_drawPanelMouseDragged

    private void drawPanelMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_drawPanelMouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_drawPanelMouseWheelMoved

    private void chkShowTCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkShowTCPActionPerformed
        drawPanel.setTransitionsControlPointsVisible( chkShowTCP.isSelected() );
        drawPanel.repaint();
    }//GEN-LAST:event_chkShowTCPActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAddState;
    private javax.swing.JToggleButton btnAddTransition;
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JToggleButton btnMove;
    private javax.swing.JButton btnReset;
    private javax.swing.JCheckBox chkShowTCP;
    private br.com.davidbuzatto.yaas.gui.DrawPanel drawPanel;
    private javax.swing.JToolBar.Separator sep01;
    private javax.swing.JToolBar toolBar;
    // End of variables declaration//GEN-END:variables
}
