/*
 * Copyright (C) 2022 Prof. Dr. David Buzatto
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package br.com.davidbuzatto.yaas.gui;

import br.com.davidbuzatto.yaas.gui.fa.FAInternalFrame;
import br.com.davidbuzatto.yaas.util.ApplicationPreferences;
import br.com.davidbuzatto.yaas.util.CharacterConstants;
import br.com.davidbuzatto.yaas.util.Utils;
import com.formdev.flatlaf.FlatDarculaLaf;

/**
 * Main GUI class.
 * 
 * @author Prof. Dr. David Buzatto
 */
public class MainWindow extends javax.swing.JFrame {
    
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        ApplicationPreferences.preparePreferences( false );
        initComponents();
        customInit();
    }
    
    private void customInit() {
        
        setTitle( 
                Utils.getMavenModel().getArtifactId() + 
                " - v" + 
                Utils.getMavenModel().getVersion() );
        
        //setExtendedState( MAXIMIZED_BOTH );
        
        FAInternalFrame iFrame = new FAInternalFrame( this );
        desktopPane.add( iFrame );
        iFrame.setVisible( true );
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        toolBar = new javax.swing.JToolBar();
        btnFA = new javax.swing.JButton();
        btnPDA = new javax.swing.JButton();
        btnTM = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuItemExit = new javax.swing.JMenuItem();
        menuExamples = new javax.swing.JMenu();
        menuDFA = new javax.swing.JMenu();
        menuNFA = new javax.swing.JMenu();
        menuENFA = new javax.swing.JMenu();
        menuHelp = new javax.swing.JMenu();
        menuItemAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("YAAS");
        setIconImage(new javax.swing.ImageIcon( getClass().getResource( "/yaas.png" ) ).getImage());

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 631, Short.MAX_VALUE)
        );

        toolBar.setRollover(true);

        btnFA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/faBig.png"))); // NOI18N
        btnFA.setText("Finite Automata");
        btnFA.setToolTipText("");
        btnFA.setFocusable(false);
        btnFA.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFA.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFAActionPerformed(evt);
            }
        });
        toolBar.add(btnFA);

        btnPDA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pdaBig.png"))); // NOI18N
        btnPDA.setText("Pushdown Automata");
        btnPDA.setToolTipText("");
        btnPDA.setEnabled(false);
        btnPDA.setFocusable(false);
        btnPDA.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPDA.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(btnPDA);

        btnTM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/turingBig.png"))); // NOI18N
        btnTM.setText("Turing Machines");
        btnTM.setEnabled(false);
        btnTM.setFocusable(false);
        btnTM.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTM.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(btnTM);

        menuFile.setText("File");

        menuItemExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuItemExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/door_out.png"))); // NOI18N
        menuItemExit.setText("Exit");
        menuFile.add(menuItemExit);

        menuBar.add(menuFile);

        menuExamples.setText("Examples");

        menuDFA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dfa.png"))); // NOI18N
        menuDFA.setText("DFA");
        menuExamples.add(menuDFA);

        menuNFA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nfa.png"))); // NOI18N
        menuNFA.setText("NFA");
        menuExamples.add(menuNFA);

        menuENFA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enfa.png"))); // NOI18N
        menuENFA.setText(CharacterConstants.EMPTY_STRING.toString() + "-NFA");
        menuExamples.add(menuENFA);

        menuBar.add(menuExamples);

        menuHelp.setText("Help");

        menuItemAbout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        menuItemAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/help.png"))); // NOI18N
        menuItemAbout.setText("About...");
        menuHelp.add(menuItemAbout);

        menuBar.add(menuHelp);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
            .addComponent(toolBar, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(toolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desktopPane))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFAActionPerformed
        FAInternalFrame iFrame = new FAInternalFrame( this );
        desktopPane.add( iFrame );
        iFrame.setVisible( true );
    }//GEN-LAST:event_btnFAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main( String args[] ) {
        java.awt.EventQueue.invokeLater( new Runnable() {
            public void run() {
                FlatDarculaLaf.setup();
                new MainWindow().setVisible( true );
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFA;
    private javax.swing.JButton btnPDA;
    private javax.swing.JButton btnTM;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuDFA;
    private javax.swing.JMenu menuENFA;
    private javax.swing.JMenu menuExamples;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenuItem menuItemAbout;
    private javax.swing.JMenuItem menuItemExit;
    private javax.swing.JMenu menuNFA;
    private javax.swing.JToolBar toolBar;
    // End of variables declaration//GEN-END:variables
}
