/*
 * Copyright (C) 2023 Prof. Dr. David Buzatto
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package br.com.davidbuzatto.yaas.gui.pda.properties;

import br.com.davidbuzatto.yaas.gui.pda.PDAFormalDefinitionDialog;
import br.com.davidbuzatto.yaas.gui.pda.PDAInternalFrame;
import br.com.davidbuzatto.yaas.model.pda.PDA;
import br.com.davidbuzatto.yaas.util.Utils;
import java.util.ArrayList;
import java.util.List;

/**
 * Pushdown Automaton properties edit/visualization panel.
 * 
 * @author Prof. Dr. David Buzatto
 */
public class PDAPropertiesPanel extends javax.swing.JPanel {

    private PDAInternalFrame pdaIFrame;
    
    private PDA pda;
    
    /**
     * Creates new form FAPropertiesPanel
     */
    public PDAPropertiesPanel( PDAInternalFrame pdaIFrame ) {
        
        this.pdaIFrame = pdaIFrame;
        
        initComponents();
        customInit();
        
    }
    
    private void customInit() {
    }

    public void setPda( PDA pda ) {
        this.pda = pda;
    }

    public void readProperties() {
        String s = "";
        for ( char c : pda.getStartingPushSymbols() ) {
            s += c + " ";
        }
        txtStartingPush.setText( s.trim() );
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFormalDefinition = new javax.swing.JButton();
        lblStartingPush = new javax.swing.JLabel();
        txtStartingPush = new javax.swing.JTextField();

        btnFormalDefinition.setText("Formal Definition");
        btnFormalDefinition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormalDefinitionActionPerformed(evt);
            }
        });

        lblStartingPush.setText("Starting Push:");

        txtStartingPush.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtStartingPushFocusLost(evt);
            }
        });
        txtStartingPush.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStartingPushActionPerformed(evt);
            }
        });
        txtStartingPush.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtStartingPushKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnFormalDefinition)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblStartingPush)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStartingPush, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStartingPush)
                    .addComponent(txtStartingPush, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFormalDefinition)
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnFormalDefinitionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormalDefinitionActionPerformed
        
        if ( pda.getStates().isEmpty() ) {
            Utils.showWarningMessage( pdaIFrame, "First add at least one state!" );
        } else if ( pda.getInitialState() == null ) {
            Utils.showWarningMessage( pdaIFrame, "Set the initial state!" );
        } else {
            PDAFormalDefinitionDialog d = new PDAFormalDefinitionDialog( null, true, pda );
            d.setVisible( true );
        }
        
    }//GEN-LAST:event_btnFormalDefinitionActionPerformed

    private void txtStartingPushActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStartingPushActionPerformed
        updateStartingPushSymbols();
    }//GEN-LAST:event_txtStartingPushActionPerformed

    private void txtStartingPushFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtStartingPushFocusLost
        updateStartingPushSymbols();
    }//GEN-LAST:event_txtStartingPushFocusLost

    private void txtStartingPushKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStartingPushKeyReleased
        updateStartingPushSymbols();
    }//GEN-LAST:event_txtStartingPushKeyReleased

    private void updateStartingPushSymbols() {
        
        String input = txtStartingPush.getText().trim().replaceAll( " ", "" );
        
        if ( !input.isEmpty() ) {
            List<Character> s = new ArrayList<>();
            for ( char c : input.toCharArray() ) {
                s.add( c );
            }
            pda.setStartingPushSymbols( s );
        } else {
            pda.setStartingPushSymbols( new ArrayList<>() );
        }
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFormalDefinition;
    private javax.swing.JLabel lblStartingPush;
    private javax.swing.JTextField txtStartingPush;
    // End of variables declaration//GEN-END:variables
}
