/*
 * Copyright (C) 2023 Prof. Dr. David Buzatto
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package br.com.davidbuzatto.yaas.gui.pda;

import br.com.davidbuzatto.yaas.model.pda.PDA;
import br.com.davidbuzatto.yaas.model.pda.PDAAcceptanceType;
import br.com.davidbuzatto.yaas.util.CharacterConstants;
import java.awt.Frame;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 * A dialog for batch testing strings against Pushdown Automata.
 * 
 * @author Prof. Dr. David Buzatto
 */
public class PDABatchTest extends javax.swing.JDialog {

    private PDAInternalFrame pdaIFrame;
    private PDAAcceptanceType acceptanceType;
    
    private PDA pda;
    
    /**
     * Creates new form FABatchTest
     */
    public PDABatchTest( Frame parent, PDAInternalFrame pdaIFrame, PDAAcceptanceType acceptanceType, boolean modal ) {
        super( parent, modal );
        this.pdaIFrame = pdaIFrame;
        this.acceptanceType = acceptanceType;
        initComponents();
        customInit();
        setLocationRelativeTo( pdaIFrame );
    }

    private void customInit() {
        setIconImage( new ImageIcon( getClass().getResource( "/book.png" ) ).getImage() );
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelStrings = new javax.swing.JPanel();
        scrollStrings = new javax.swing.JScrollPane();
        textAreaStrings = new javax.swing.JTextArea();
        btnTest = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setTitle("Batch Test");
        setResizable(false);

        panelStrings.setBorder(javax.swing.BorderFactory.createTitledBorder("Strings"));

        textAreaStrings.setColumns(20);
        textAreaStrings.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        textAreaStrings.setRows(5);
        scrollStrings.setViewportView(textAreaStrings);

        javax.swing.GroupLayout panelStringsLayout = new javax.swing.GroupLayout(panelStrings);
        panelStrings.setLayout(panelStringsLayout);
        panelStringsLayout.setHorizontalGroup(
            panelStringsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStringsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollStrings, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelStringsLayout.setVerticalGroup(
            panelStringsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStringsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollStrings, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnTest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/accept.png"))); // NOI18N
        btnTest.setText("Test");
        btnTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestActionPerformed(evt);
            }
        });

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancel.png"))); // NOI18N
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelStrings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnTest)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClose)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelStrings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClose)
                    .addComponent(btnTest))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestActionPerformed
        
        String[] strings = textAreaStrings.getText().split( "\n" );
        
        StringBuilder sb = new StringBuilder();
        boolean first = true;
        
        for ( String str : strings ) {
            
            boolean accepted = pda.accepts( str, acceptanceType );
            
            if ( !first ) {
                sb.append( "\n" );
            }
            
            sb.append( String.format( "%s %c L(A)", 
                    str.isEmpty() ? 
                            CharacterConstants.EMPTY_STRING.toString() : 
                            str, 
                    accepted ? 
                            CharacterConstants.ELEMENT_OF : 
                            CharacterConstants.NOT_ELEMENT_OF ) );
            
            first = false;
            
        }
        
        JTextArea ta = new JTextArea( sb.toString(), 10, 32 );
        ta.setFont( textAreaStrings.getFont() );
        ta.setEditable( false );
        JScrollPane sp = new JScrollPane( ta );
        
        JOptionPane.showMessageDialog( 
                this, 
                sp, 
                "Batch Test Results", 
                JOptionPane.INFORMATION_MESSAGE );
        
    }//GEN-LAST:event_btnTestActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        setVisible( false );
    }//GEN-LAST:event_btnCloseActionPerformed

    public void setPda( PDA pda ) {
        this.pda = pda;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnTest;
    private javax.swing.JPanel panelStrings;
    private javax.swing.JScrollPane scrollStrings;
    private javax.swing.JTextArea textAreaStrings;
    // End of variables declaration//GEN-END:variables
}
